name: test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run gipr
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_user_name: GitHub Actions
          git_user_email: github-actions@example.cpm
          timezone: Asia/Tokyo
